# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
jobs:
  test:
    executor:
      name: node/default
      tag: '18.12'
    steps:
      - checkout
      - node/install-packages
      - run:
          command: npm run test
workflows:
  test_my_app:
    jobs:
      - test